lane :deploy do
  build_app(scheme: "DVRO")

  deliver(
    force: true,                    # Força o envio sem prompt interativo
    itc_team_id: 'Z72V34LC55',  # ID do time, recebido da variável de ambiente
    skip_metadata: true,            # Pula atualização de metadados, se desejado
    skip_screenshots: true,         # Pula envio de screenshots, se não for necessário
    submit_for_review: false        # Altere para true se quiser enviar para revisão automaticamente
  )
end
