# frozen_string_literal: true
gem 'rexml', '~> 3.2.5'

source "https://rubygems.org"

# gem "rails"

gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz/apple-auth-sirp"