default_platform(:ios)

platform :ios do
  desc "Deploy (gera .ipa e envia para TestFlight/App Store)"
  lane :deploy do
    build_app(
      workspace: "DVRO.xcworkspace",
      scheme: "DVRO",
      configuration: "Release",
      export_method: "app-store"
    )

    upload_to_app_store(
      app_identifier: "br.com.delivery.app",
      apple_id: '6467809101',
      team_id: 'Z72V34LC55',
      itc_provider: ENV["APPLE_ITC_PROVIDER"],
      skip_metadata: true,
      skip_screenshots: true
    )
  end

  desc "Cria o app no App Store Connect (caso não exista)"
  lane :create_app do
    produce(
      app_identifier: "br.com.delivery.app",
      app_name: "SeuApp",
      language: "English",
      sku: "seuapp-sku-123"
    )
  end
end
