-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0TvizRmd/oThBMmz
M0YNJrkn5GGypxyPAh76grKPPTygCgYIKoZIzj0DAQehRANCAATYZu7mtJJoWEAU
TGNwiX3mzhdg/MK/XMWLs2paEMHawpLZqi6N/3IN98XBLxNC6yja4d/4NJ3AZaO1
KyifTQHt
-----END PRIVATE KEY-----