name: iOS Build and Deploy (Sem Fastlane)

on:
  push:
    branches-ignore: ["master"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Install Node dependencies
        run: npm install --force
      - name: Install CocoaPods dependencies
        working-directory: ios
        run: pod install

      - name: Build e Archive
        run: |
          xcodebuild clean archive \
            -workspace ios/DVRO.xcworkspace \
            -scheme DVRO \
            -configuration Release \
            -archivePath $PWD/build/DVRO.xcarchive

      - name: Exportar IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath $PWD/build/DVRO.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            git  -exportPath $PWD/build/IPA

      - name: Upload para App Store Connect
        run: |
          xcrun altool --upload-app \
            -f $PWD/build/IPA/SeuApp.ipa \
            -t ios \
            -u $APPLE_ID \
            -p $APPLE_SPECIFIC_PASSWORD
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_SPECIFIC_PASSWORD }}
