name: Build & Publish Android (S3 Keystore)

on:
  push:
    branches-ignore: ["main"]
  workflow_dispatch:

jobs:
  publish-android:
    runs-on: macos-latest

    steps:
      # 1) Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Instalar AWS CLI
      - name: Install AWS CLI
        run: |
          brew install awscli

      - name: Download Keystore from S3
        run: |
          # Configura credenciais AWS diretamente (conforme solicitado)
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region "us-east-2"

          # Baixa o keystore (exemplo: "thefamous-olga.keystore")
          aws s3 cp "s3://app-generator-robson/keystores/thefamous-olga.keystore" "android/app/thefamous-olga.keystore"

          echo "Listando arquivos em android/app/ para conferir:"
          ls -la android/app/

      # 4) Configurar Java (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      # 5) Configurar Node (para React Native, se necessário)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 6) Configurar Ruby (para Fastlane)
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      # 7) Instalar dependências do projeto
      - name: Install Dependencies
        run: npm install --force

      # 8) Criar arquivo google-play-key.json (caso use supply)
      - name: Create Google JSON
        run: |
          echo "${{ secrets.ANDROID_JSON_KEY }}" > android/fastlane/google-play-key.json

      # 9) Instalar o Fastlane
      - name: Install Fastlane
        run: gem install fastlane

      # 10) Executar Build & Deploy do Android
      - name: Deploy Android
        run: |
          cd android
          fastlane deploy || (fastlane create_app && fastlane deploy)

      # 11) Remover o keystore local (para não ficar no runner)
      - name: Remove Keystore
        run: |
          rm -f android/app/thefamous-olga.keystore
          echo "Keystore removido do runner."
