name: Build & Publish Android e iOS (S3 Keystore)

on:
  push:
    branches-ignore: ["master"]
  workflow_dispatch:

jobs:
  publish-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Clear Gem Cache
        run: |
          gem sources --remove https://rubygems.org/
          gem sources -a https://rubygems.org/
          gem cleanup
          gem uninstall boost -aIx || true

      - name: Update CocoaPods
        run: sudo gem install cocoapods

      - name: Clear CocoaPods Cache
        run: pod cache clean --all

      - name: Install Dependencies
        run: npm install --force

      - name: Install Additional Dependencies
        run: |
          npm install --save-dev patch-package postinstall-postinstall --force

      # --- Novo passo: Patch no podspec do boost ---
      - name: Patch boost podspec URL and checksum
        run: |
          cd ios
          # Substitui a URL antiga pela nova
          sed -i '' 's|https://dl.bintray.com/boostorg/release/1.76.0/source/boost_1_76_0.tar.bz2|https://archives.boost.io/release/1.76.0/source/boost_1_76_0.tar.bz2|g' ../node_modules/react-native/third-party-podspecs/boost.podspec
          # Substitui o checksum antigo pelo novo
          sed -i '' 's/f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41/79e6d3f986444e5a80afbeccdaf2d1c1cf964baa8d766d20859d653a16c39848/g' ../node_modules/react-native/third-party-podspecs/boost.podspec

      - name: Install pod dependencies
        run: |
          cd ios
          sudo rm -rf Podfile.lock
          pod install --no-repo-update

      - name: Install Fastlane
        run: gem install fastlane

      - name: Create API Key
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" | base64 --decode > android/AuthKey_OLGA.p8

      - name: Debug API Key
        run: |
          echo "==== Conteúdo do AuthKey_OLGA.p8 ===="
          cat android/AuthKey_OLGA.p8
          echo "======================================"

      - name: Build & Deploy iOS
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_SPECIFIC_PASSWORD }}
          CERT_GIT: ${{ secrets.GH_TOKEN_REPO }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          cd android
          fastlane ios deploy_ios

      - name: Notify Discord (iOS)
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            curl -X POST -H "Content-Type: application/json" \
              -d '{"content":"✅ Build & publicação do iOS *SUCESSO*! "}' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
          else
            curl -X POST -H "Content-Type: application/json" \
              -d '{"content":"❌ Build & publicação do iOS *FALHOU*."}' \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
          fi
