name: Build & Publish Android and iOS (S3 Keystore)

on:
  push:
    branches-ignore: ["master"]
  workflow_dispatch:

# Cancela builds em andamento na mesma branch
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-android:
    runs-on: macos-latest

    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Instalar AWS CLI (via brew)
      - name: Install AWS CLI
        run: brew install awscli

      # 3) Baixar Keystore do S3
      - name: Download Keystore from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2  
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region "$AWS_DEFAULT_REGION"
          aws s3 cp "s3://app-generator-robson/keystores/thefamous-olga.keystore" "android/app/thefamous-olga.keystore"

      # 4) Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 5) Configurar Node 18
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 6) Cache de dependências Node
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 7) Instalar dependências (Node)
      - name: Install Dependencies
        run: npm ci

      # 8) Criar google-play-key.json
      - name: Create Google JSON
        run: echo "${{ secrets.ANDROID_JSON_KEY }}" | base64 --decode > android/google-play-key.json

      # 9) Configurar Ruby e instalar dependências (Fastlane)
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Cache Bundler
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-
      - name: Install Fastlane
        run: gem install fastlane

      # 10) Build & Deploy Android
      - name: Deploy Android
        run: |
          cd android
          fastlane deploy || (fastlane create_app && fastlane deploy)

      # 11) Remover o keystore do runner
      - name: Remove Keystore
        run: rm -f android/app/thefamous-olga.keystore

  publish-ios:
    runs-on: macos-latest
    needs: publish-android  # Executa depois do Android

    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Configurar Ruby
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Cache Bundler
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-

      # 3) Instalar Fastlane
      - name: Install Fastlane
        run: gem install fastlane

      # 4) Criar arquivo da API Key .p8
      - name: Create API Key
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" | base64 --decode > AuthKey_OLGA.p8

      # 5) Validar existência do arquivo
      - name: Check Key File
        run: |
          if [ ! -f "./AuthKey_OLGA.p8" ]; then
            echo "Erro: AuthKey_OLGA.p8 não encontrado!"
            exit 1
          fi

      # 6) Sincronizar Certificados e Profiles (Match)
      - name: Sync Certificates and Profiles
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_SPECIFIC_PASSWORD }}
        run: fastlane match appstore

      # 7) Build & Deploy iOS
      - name: Build & Deploy iOS
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_SPECIFIC_PASSWORD }}
        run: fastlane ios deploy

      # 8) Limpeza final (opcional)
      - name: Remove Key File
        run: rm -f AuthKey_OLGA.p8
