name: iOS Build & Archive

on:
  push:
    branches-ignore: ["master"]
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'  # Use uma versão compatível

      - name: Install Gems
        run: bundle install

      - name: Sync Certificates and Provisioning Profiles with Match
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: "https://seu-repositorio-privado.git"
        run: bundle exec fastlane match development

      - name: Install CocoaPods Dependencies
        working-directory: ios
        run: pod install --repo-update

      - name: Build and Archive
        run: |
          xcodebuild clean archive \
            -workspace ios/DVRO.xcworkspace \
            -scheme DVRO \
            -configuration Release \
            -archivePath $PWD/build/DVRO.xcarchive \
            -allowProvisioningUpdates