name: Deploy to App Store

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: macos-latest
    strategy:
      matrix:
        # Insira os IDs (ou nomes) das equipes correspondentes a cada cliente
        team: 
          - Z72V34LC55
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # ou a versão que você utiliza

      - name: Install fastlane
        run: gem install fastlane

      - name: Build App
        run: fastlane build   # Substitua pela lane de build do seu projeto

      - name: Deploy to App Store for team ${{ matrix.team }}
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          ITC_TEAM_ID: ${{ matrix.team }}
        run: fastlane deploy   # Lane de deploy configurada para usar ITC_TEAM_ID
