name: Build & Publish

on:
  push:
    branches-ignore: ["master"]
  workflow_dispatch:

jobs:
  publish-android:
    runs-on: macos-latest

    steps:
      # 1) Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Setup Node + Cache (opcional, se seu projeto RN precisar rodar npm ci)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install --force

      # 3) Instalar Ruby + Cache
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Cache Bundler
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-

      # 4) Instalar Gems (Fastlane e afins)
      - name: Install Gems
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      # 5) Instalar AWS CLI (se precisar baixar keystore do S3)
      - name: Install AWS CLI
        run: brew install awscli

      # 6) Baixar keystore do S3
      - name: Download Keystore
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set default.region "$AWS_DEFAULT_REGION"
          aws s3 cp "s3://app-generator-robson/keystores/thefamous-olga.keystore" "android/app/thefamous-olga.keystore"

      # 7) Criar JSON da Play Store
      - name: Create Google Play Key
        run: echo "${{ secrets.ANDROID_JSON_KEY }}" | base64 --decode > android/google-play-key.json

      # 8) Deploy Android (tenta -> se falhar, create_app -> tenta de novo)
      - name: Deploy Android
        run: |
          bundle install
          bundle exec fastlane android deploy || (bundle exec fastlane android create_app && bundle exec fastlane android deploy)
      # 9) Remove keystore no final (limpeza)
      - name: Remove Keystore
        run: rm -f android/app/thefamous-olga.keystore

  publish-ios:
    runs-on: macos-latest
    needs: publish-android  # só roda depois do Android

    steps:
      # 1) Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2) Setup Ruby + Cache Bundler
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Cache Bundler
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-

      - name: Install Gems
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      # 3) Criar AuthKey_OLGA.p8
      - name: Create .p8
        run: echo "${{ secrets.APP_STORE_CONNECT_API_KEY }}" | base64 --decode > ios/AuthKey_OLGA.p8

      # 4) Verificar se o arquivo foi criado
      - name: Debug .p8
        run: ls -l ios/AuthKey_OLGA.p8

      # 5) Build & Deploy iOS
      - name: Deploy iOS
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_SPECIFIC_PASSWORD }}
        run: |
          cd ios
          bundle exec fastlane ios deploy

      # 6) Limpar chave
      - name: Remove .p8
        run: rm -f ios/AuthKey_OLGA.p8
